engine:
  engine_type: renpy
paths:
  input_dir: input
  log_dir: logs
  output_dir: output
  param_config_dir: param_config
processing:
  batch_size: 100
  enable_progress_bar: false
  ignore_mode: false
  ignore_words:
  - 忽略
  - ''
